INSERT INTO patients ('first_name', 'last_name', 'age') VALUES ('Season',   'Pennel',     47);
INSERT INTO patients ('first_name', 'last_name', 'age') VALUES ('Fairy',    'Breen',      48);
INSERT INTO patients ('first_name', 'last_name', 'age') VALUES ('Josefine', 'Dietrich',   61);
INSERT INTO patients ('first_name', 'last_name', 'age') VALUES ('Jaymie',   'Plummer',    21);
INSERT INTO patients ('first_name', 'last_name', 'age') VALUES ('Ezra',     'Rawls',      29);
INSERT INTO patients ('first_name', 'last_name', 'age') VALUES ('Elly',     'Lafleur',    30);
INSERT INTO patients ('first_name', 'last_name', 'age') VALUES ('Bette',    'Davenport',  21);
INSERT INTO patients ('first_name', 'last_name', 'age') VALUES ('Zona',     'Boland',     11);
INSERT INTO patients ('first_name', 'last_name', 'age') VALUES ('Marg',     'Womack',     74);
INSERT INTO patients ('first_name', 'last_name', 'age') VALUES ('Mellie',   'Thorne',     46);

INSERT INTO doctors ('first_name', 'last_name', 'specialty') VALUES ('Gregory',  'House',       'Infectious Disease Specialist');
INSERT INTO doctors ('first_name', 'last_name', 'specialty') VALUES ('Lisa',     'Cuddy',       'Endocrinologist');
INSERT INTO doctors ('first_name', 'last_name', 'specialty') VALUES ('James',    'Wilson',      'Oncologist');
INSERT INTO doctors ('first_name', 'last_name', 'specialty') VALUES ('Eric',     'Foreman',     'Neurologist');
INSERT INTO doctors ('first_name', 'last_name', 'specialty') VALUES ('Robert',   'Chase',       'Cardiac Surgery');
INSERT INTO doctors ('first_name', 'last_name', 'specialty') VALUES ('Allison',  'Cameron',     'Immunologist');
INSERT INTO doctors ('first_name', 'last_name', 'specialty') VALUES ('Thirteen', 'Remy Hadley', 'Infectious Disease Specialist');

INSERT INTO consultations ('doctor_id', 'patient_id', 'created_at') VALUES (3, 1,  '2016-09-25');
INSERT INTO consultations ('doctor_id', 'patient_id', 'created_at') VALUES (4, 5,  '2016-12-16');
INSERT INTO consultations ('doctor_id', 'patient_id', 'created_at') VALUES (1, 8,  '2016-11-25');
INSERT INTO consultations ('doctor_id', 'patient_id', 'created_at') VALUES (6, 5,  '2016-11-01');
INSERT INTO consultations ('doctor_id', 'patient_id', 'created_at') VALUES (5, 2,  '2016-09-23');
INSERT INTO consultations ('doctor_id', 'patient_id', 'created_at') VALUES (1, 4,  '2016-11-11');
INSERT INTO consultations ('doctor_id', 'patient_id', 'created_at') VALUES (4, 9,  '2016-10-25');
INSERT INTO consultations ('doctor_id', 'patient_id', 'created_at') VALUES (4, 1,  '2016-12-10');
INSERT INTO consultations ('doctor_id', 'patient_id', 'created_at') VALUES (3, 7,  '2016-11-10');
INSERT INTO consultations ('doctor_id', 'patient_id', 'created_at') VALUES (6, 7,  '2016-12-23');
INSERT INTO consultations ('doctor_id', 'patient_id', 'created_at') VALUES (4, 1,  '2016-11-04');
INSERT INTO consultations ('doctor_id', 'patient_id', 'created_at') VALUES (4, 6,  '2016-09-28');
INSERT INTO consultations ('doctor_id', 'patient_id', 'created_at') VALUES (2, 3,  '2016-12-21');
INSERT INTO consultations ('doctor_id', 'patient_id', 'created_at') VALUES (3, 10, '2016-12-21');
INSERT INTO consultations ('doctor_id', 'patient_id', 'created_at') VALUES (2, 8,  '2016-12-28');
INSERT INTO consultations ('doctor_id', 'patient_id', 'created_at') VALUES (5, 2,  '2016-10-06');
